# Generated by Django 5.0.6 on 2024-05-20 22:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservadb',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('no_disponible', 'No Disponible')], default='disponible', max_length=13),
        ),
        migrations.RemoveField(
            model_name='reservapromociondb',
            name='promocion',
        ),
        migrations.RemoveField(
            model_name='reservadb',
            name='promociones',
        ),
        migrations.RemoveField(
            model_name='reservapromociondb',
            name='reserva',
        ),
        migrations.RemoveField(
            model_name='canchadb',
            name='tipo',
        ),
        migrations.AddField(
            model_name='canchadb',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariodb',
            name='apellido',
            field=models.CharField(default=0.0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariodb',
            name='dni',
            field=models.CharField(default=0, max_length=8, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator('^\\d{8}$', message='El DNI debe contener exactamente 8 dígitos.')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuariodb',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='EstadoReservaDb',
        ),
        migrations.DeleteModel(
            name='PromocionDb',
        ),
        migrations.DeleteModel(
            name='ReservaPromocionDb',
        ),
    ]
