# Generated by Django 5.0.6 on 2024-05-20 22:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_alter_reservadb_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canchadb',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usuariodb',
            name='dni',
            field=models.CharField(default='00000000', max_length=8, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator('^\\d{8}$', message='El DNI debe contener exactamente 8 dígitos.')]),
        ),
    ]
