# Generated by Django 5.0.6 on 2024-05-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_alter_canchadb_precio_alter_usuariodb_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariodb',
            name='apellido',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
