# Generated by Django 5.0.6 on 2024-05-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_alter_usuariodb_apellido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariodb',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='reservadb',
            unique_together={('fecha', 'hora', 'cancha')},
        ),
    ]
