# Generated by Django 5.0.6 on 2024-05-21 00:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_alter_reservadb_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservadb',
            name='estado',
            field=models.CharField(default='disponible', editable=False, max_length=13),
        ),
        migrations.AlterField(
            model_name='usuariodb',
            name='dni',
            field=models.CharField(default='', max_length=8, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator('^\\d{8}$', message='El DNI debe contener exactamente 8 dígitos.')]),
        ),
        migrations.AlterField(
            model_name='usuariodb',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Por favor, introduce una dirección de correo electrónico válida')]),
        ),
    ]
