# Generated by Django 5.0.6 on 2024-05-21 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0008_remove_reservadb_estado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservadb',
            unique_together={('fecha', 'hora', 'cancha')},
        ),
    ]
